# coding: utf-8

"""
    Synonyms API

    Retrieves the sets of synonyms for a given word.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.synonym_dictionary_list import SynonymDictionaryList  # noqa: E501
from swagger_client.rest import ApiException


class TestSynonymDictionaryList(unittest.TestCase):
    """SynonymDictionaryList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSynonymDictionaryList(self):
        """Test SynonymDictionaryList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.synonym_dictionary_list.SynonymDictionaryList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
