# coding: utf-8

"""
    Synonyms API

    Retrieves the sets of synonyms for a given word.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.synonyms_api import SynonymsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSynonymsApi(unittest.TestCase):
    """SynonymsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.synonyms_api.SynonymsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_designations(self):
        """Test case for get_designations

        """
        pass

    def test_get_number_words(self):
        """Test case for get_number_words

        """
        pass

    def test_get_prefixes(self):
        """Test case for get_prefixes

        """
        pass

    def test_get_synonyms(self):
        """Test case for get_synonyms

        """
        pass

    def test_get_transform_text(self):
        """Test case for get_transform_text

        """
        pass

    def test_get_word_stops(self):
        """Test case for get_word_stops

        """
        pass

    def test_get_word_substitutions(self):
        """Test case for get_word_substitutions

        """
        pass

    def test_get_word_synonyms(self):
        """Test case for get_word_synonyms

        """
        pass


if __name__ == '__main__':
    unittest.main()
