# coding: utf-8

"""
    Synonyms API

    Retrieves the sets of synonyms for a given word.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.string import String  # noqa: E501
from swagger_client.rest import ApiException


class TestString(unittest.TestCase):
    """String unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testString(self):
        """Test String"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.string.String()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
