# coding: utf-8

"""
    Synonyms API

    Retrieves the sets of synonyms for a given word.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.synonyms_api import SynonymsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSynonymsApi(unittest.TestCase):
    """SynonymsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.synonyms_api.SynonymsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_all_any_designations(self):
        """Test case for get_all_any_designations

        """
        pass

    def test_get_all_end_designations(self):
        """Test case for get_all_end_designations

        """
        pass

    def test_get_all_substitutions_synonyms(self):
        """Test case for get_all_substitutions_synonyms

        """
        pass

    def test_get_designated_any_all_words(self):
        """Test case for get_designated_any_all_words

        """
        pass

    def test_get_designated_end_all_words(self):
        """Test case for get_designated_end_all_words

        """
        pass

    def test_get_designation_all_in_name(self):
        """Test case for get_designation_all_in_name

        """
        pass

    def test_get_designation_any_in_name(self):
        """Test case for get_designation_any_in_name

        """
        pass

    def test_get_designation_end_in_name(self):
        """Test case for get_designation_end_in_name

        """
        pass

    def test_get_designations(self):
        """Test case for get_designations

        """
        pass

    def test_get_entity_type_any_designation(self):
        """Test case for get_entity_type_any_designation

        """
        pass

    def test_get_entity_type_by_value(self):
        """Test case for get_entity_type_by_value

        """
        pass

    def test_get_entity_type_end_designation(self):
        """Test case for get_entity_type_end_designation

        """
        pass

    def test_get_exception_regex(self):
        """Test case for get_exception_regex

        """
        pass

    def test_get_incorrect_designation_end_in_name(self):
        """Test case for get_incorrect_designation_end_in_name

        """
        pass

    def test_get_misplaced_any_designations(self):
        """Test case for get_misplaced_any_designations

        """
        pass

    def test_get_misplaced_end_designations(self):
        """Test case for get_misplaced_end_designations

        """
        pass

    def test_get_number_words(self):
        """Test case for get_number_words

        """
        pass

    def test_get_prefixes(self):
        """Test case for get_prefixes

        """
        pass

    def test_get_regex_prefixes(self):
        """Test case for get_regex_prefixes

        """
        pass

    def test_get_stop_words(self):
        """Test case for get_stop_words

        """
        pass

    def test_get_synonyms(self):
        """Test case for get_synonyms

        """
        pass

    def test_get_transform_text(self):
        """Test case for get_transform_text

        """
        pass

    def test_get_word_substitutions(self):
        """Test case for get_word_substitutions

        """
        pass

    def test_get_word_synonyms(self):
        """Test case for get_word_synonyms

        """
        pass


if __name__ == '__main__':
    unittest.main()
