# coding: utf-8

# flake8: noqa

"""
    Synonyms API

    Retrieves the sets of synonyms for a given word.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.name_processing_api import NameProcessingApi
from swagger_client.api.probes_api import ProbesApi
from swagger_client.api.synonyms_api import SynonymsApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.dictionary_list import DictionaryList
from swagger_client.models.string import String
from swagger_client.models.synonym_dictionary_list import SynonymDictionaryList
from swagger_client.models.synonym_list import SynonymList
