# coding: utf-8

# flake8: noqa
"""
    Synonyms API

    Retrieves the sets of synonyms for a given word.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.dictionary_list import DictionaryList
from swagger_client.models.string import String
from swagger_client.models.synonym_dictionary_list import SynonymDictionaryList
from swagger_client.models.synonym_list import SynonymList
