# coding: utf-8

"""
    Synonyms API

    Retrieves the sets of synonyms for a given word.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class SynonymsApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def get_all_any_designations(self, **kwargs):  # noqa: E501
        """get_all_any_designations  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_all_any_designations(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: SynonymDictionaryList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_all_any_designations_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_all_any_designations_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_all_any_designations_with_http_info(self, **kwargs):  # noqa: E501
        """get_all_any_designations  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_all_any_designations_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: SynonymDictionaryList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_all_any_designations" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/synonyms/all-any-designations', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SynonymDictionaryList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_all_end_designations(self, **kwargs):  # noqa: E501
        """get_all_end_designations  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_all_end_designations(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: SynonymDictionaryList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_all_end_designations_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_all_end_designations_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_all_end_designations_with_http_info(self, **kwargs):  # noqa: E501
        """get_all_end_designations  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_all_end_designations_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: SynonymDictionaryList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_all_end_designations" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/synonyms/all-end-designations', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SynonymDictionaryList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_all_substitutions_synonyms(self, **kwargs):  # noqa: E501
        """get_all_substitutions_synonyms  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_all_substitutions_synonyms(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str words: 
        :param str words_are_distinctive: 
        :return: SynonymDictionaryList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_all_substitutions_synonyms_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_all_substitutions_synonyms_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_all_substitutions_synonyms_with_http_info(self, **kwargs):  # noqa: E501
        """get_all_substitutions_synonyms  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_all_substitutions_synonyms_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str words: 
        :param str words_are_distinctive: 
        :return: SynonymDictionaryList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['words', 'words_are_distinctive']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_all_substitutions_synonyms" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'words' in params:
            query_params.append(('words', params['words']))  # noqa: E501
        if 'words_are_distinctive' in params:
            query_params.append(('words_are_distinctive', params['words_are_distinctive']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/synonyms/all-substitutions-synonyms', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SynonymDictionaryList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_designated_any_all_words(self, **kwargs):  # noqa: E501
        """get_designated_any_all_words  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_designated_any_all_words(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str entity_type_code: 
        :param str position_code: 
        :param str lang: 
        :return: SynonymList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_designated_any_all_words_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_designated_any_all_words_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_designated_any_all_words_with_http_info(self, **kwargs):  # noqa: E501
        """get_designated_any_all_words  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_designated_any_all_words_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str entity_type_code: 
        :param str position_code: 
        :param str lang: 
        :return: SynonymList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['entity_type_code', 'position_code', 'lang']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_designated_any_all_words" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'entity_type_code' in params:
            query_params.append(('entity_type_code', params['entity_type_code']))  # noqa: E501
        if 'position_code' in params:
            query_params.append(('position_code', params['position_code']))  # noqa: E501
        if 'lang' in params:
            query_params.append(('lang', params['lang']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/synonyms/designated-any-all-words', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SynonymList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_designated_end_all_words(self, **kwargs):  # noqa: E501
        """get_designated_end_all_words  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_designated_end_all_words(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str entity_type_code: 
        :param str position_code: 
        :param str lang: 
        :return: SynonymList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_designated_end_all_words_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_designated_end_all_words_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_designated_end_all_words_with_http_info(self, **kwargs):  # noqa: E501
        """get_designated_end_all_words  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_designated_end_all_words_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str entity_type_code: 
        :param str position_code: 
        :param str lang: 
        :return: SynonymList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['entity_type_code', 'position_code', 'lang']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_designated_end_all_words" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'entity_type_code' in params:
            query_params.append(('entity_type_code', params['entity_type_code']))  # noqa: E501
        if 'position_code' in params:
            query_params.append(('position_code', params['position_code']))  # noqa: E501
        if 'lang' in params:
            query_params.append(('lang', params['lang']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/synonyms/designated-end-all-words', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SynonymList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_designation_all_in_name(self, **kwargs):  # noqa: E501
        """get_designation_all_in_name  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_designation_all_in_name(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name: 
        :return: SynonymList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_designation_all_in_name_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_designation_all_in_name_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_designation_all_in_name_with_http_info(self, **kwargs):  # noqa: E501
        """get_designation_all_in_name  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_designation_all_in_name_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name: 
        :return: SynonymList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['name']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_designation_all_in_name" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'name' in params:
            query_params.append(('name', params['name']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/synonyms/designation-all-in-name', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SynonymList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_designation_any_in_name(self, **kwargs):  # noqa: E501
        """get_designation_any_in_name  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_designation_any_in_name(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name: 
        :return: SynonymList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_designation_any_in_name_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_designation_any_in_name_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_designation_any_in_name_with_http_info(self, **kwargs):  # noqa: E501
        """get_designation_any_in_name  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_designation_any_in_name_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name: 
        :return: SynonymList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['name']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_designation_any_in_name" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'name' in params:
            query_params.append(('name', params['name']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/synonyms/designation-any-in-name', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SynonymList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_designation_end_in_name(self, **kwargs):  # noqa: E501
        """get_designation_end_in_name  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_designation_end_in_name(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name: 
        :return: SynonymList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_designation_end_in_name_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_designation_end_in_name_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_designation_end_in_name_with_http_info(self, **kwargs):  # noqa: E501
        """get_designation_end_in_name  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_designation_end_in_name_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name: 
        :return: SynonymList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['name']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_designation_end_in_name" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'name' in params:
            query_params.append(('name', params['name']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/synonyms/designation-end-in-name', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SynonymList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_designations(self, **kwargs):  # noqa: E501
        """get_designations  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_designations(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str entity_type_code: 
        :param str position_code: 
        :param str lang: 
        :return: SynonymList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_designations_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_designations_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_designations_with_http_info(self, **kwargs):  # noqa: E501
        """get_designations  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_designations_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str entity_type_code: 
        :param str position_code: 
        :param str lang: 
        :return: SynonymList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['entity_type_code', 'position_code', 'lang']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_designations" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'entity_type_code' in params:
            query_params.append(('entity_type_code', params['entity_type_code']))  # noqa: E501
        if 'position_code' in params:
            query_params.append(('position_code', params['position_code']))  # noqa: E501
        if 'lang' in params:
            query_params.append(('lang', params['lang']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/synonyms/designations', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SynonymList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_entity_type_any_designation(self, **kwargs):  # noqa: E501
        """get_entity_type_any_designation  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_entity_type_any_designation(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str entity_any_designation_dict: 
        :param str all_designation_any_end_list: 
        :return: SynonymList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_entity_type_any_designation_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_entity_type_any_designation_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_entity_type_any_designation_with_http_info(self, **kwargs):  # noqa: E501
        """get_entity_type_any_designation  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_entity_type_any_designation_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str entity_any_designation_dict: 
        :param str all_designation_any_end_list: 
        :return: SynonymList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['entity_any_designation_dict', 'all_designation_any_end_list']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_entity_type_any_designation" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'entity_any_designation_dict' in params:
            query_params.append(('entity_any_designation_dict', params['entity_any_designation_dict']))  # noqa: E501
        if 'all_designation_any_end_list' in params:
            query_params.append(('all_designation_any_end_list', params['all_designation_any_end_list']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/synonyms/entity-type-any-designation', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SynonymList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_entity_type_by_value(self, **kwargs):  # noqa: E501
        """get_entity_type_by_value  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_entity_type_by_value(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str entity_type_dicts: 
        :param str designation: 
        :return: SynonymList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_entity_type_by_value_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_entity_type_by_value_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_entity_type_by_value_with_http_info(self, **kwargs):  # noqa: E501
        """get_entity_type_by_value  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_entity_type_by_value_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str entity_type_dicts: 
        :param str designation: 
        :return: SynonymList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['entity_type_dicts', 'designation']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_entity_type_by_value" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'entity_type_dicts' in params:
            query_params.append(('entity_type_dicts', params['entity_type_dicts']))  # noqa: E501
        if 'designation' in params:
            query_params.append(('designation', params['designation']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/synonyms/entity-type-by-value', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SynonymList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_entity_type_end_designation(self, **kwargs):  # noqa: E501
        """get_entity_type_end_designation  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_entity_type_end_designation(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str entity_end_designation_dict: 
        :param str all_designation_any_end_list: 
        :return: SynonymList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_entity_type_end_designation_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_entity_type_end_designation_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_entity_type_end_designation_with_http_info(self, **kwargs):  # noqa: E501
        """get_entity_type_end_designation  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_entity_type_end_designation_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str entity_end_designation_dict: 
        :param str all_designation_any_end_list: 
        :return: SynonymList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['entity_end_designation_dict', 'all_designation_any_end_list']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_entity_type_end_designation" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'entity_end_designation_dict' in params:
            query_params.append(('entity_end_designation_dict', params['entity_end_designation_dict']))  # noqa: E501
        if 'all_designation_any_end_list' in params:
            query_params.append(('all_designation_any_end_list', params['all_designation_any_end_list']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/synonyms/entity-type-end-designation', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SynonymList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_exception_regex(self, **kwargs):  # noqa: E501
        """get_exception_regex  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_exception_regex(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str text: 
        :return: SynonymList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_exception_regex_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_exception_regex_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_exception_regex_with_http_info(self, **kwargs):  # noqa: E501
        """get_exception_regex  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_exception_regex_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str text: 
        :return: SynonymList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['text']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_exception_regex" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'text' in params:
            query_params.append(('text', params['text']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/synonyms/exception-regex', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SynonymList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_incorrect_designation_end_in_name(self, **kwargs):  # noqa: E501
        """get_incorrect_designation_end_in_name  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_incorrect_designation_end_in_name(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str tokenized_name: 
        :param str designation_end_list: 
        :return: SynonymList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_incorrect_designation_end_in_name_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_incorrect_designation_end_in_name_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_incorrect_designation_end_in_name_with_http_info(self, **kwargs):  # noqa: E501
        """get_incorrect_designation_end_in_name  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_incorrect_designation_end_in_name_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str tokenized_name: 
        :param str designation_end_list: 
        :return: SynonymList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['tokenized_name', 'designation_end_list']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_incorrect_designation_end_in_name" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'tokenized_name' in params:
            query_params.append(('tokenized_name', params['tokenized_name']))  # noqa: E501
        if 'designation_end_list' in params:
            query_params.append(('designation_end_list', params['designation_end_list']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/synonyms/incorrect-designation-end-in-name', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SynonymList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_misplaced_any_designations(self, **kwargs):  # noqa: E501
        """get_misplaced_any_designations  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_misplaced_any_designations(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name: 
        :param str designation_any_entity_type: 
        :return: SynonymList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_misplaced_any_designations_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_misplaced_any_designations_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_misplaced_any_designations_with_http_info(self, **kwargs):  # noqa: E501
        """get_misplaced_any_designations  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_misplaced_any_designations_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name: 
        :param str designation_any_entity_type: 
        :return: SynonymList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['name', 'designation_any_entity_type']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_misplaced_any_designations" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'name' in params:
            query_params.append(('name', params['name']))  # noqa: E501
        if 'designation_any_entity_type' in params:
            query_params.append(('designation_any_entity_type', params['designation_any_entity_type']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/synonyms/misplaced-any-designations', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SynonymList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_misplaced_end_designations(self, **kwargs):  # noqa: E501
        """get_misplaced_end_designations  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_misplaced_end_designations(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name: 
        :param str designation_end_entity_type: 
        :return: SynonymList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_misplaced_end_designations_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_misplaced_end_designations_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_misplaced_end_designations_with_http_info(self, **kwargs):  # noqa: E501
        """get_misplaced_end_designations  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_misplaced_end_designations_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str name: 
        :param str designation_end_entity_type: 
        :return: SynonymList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['name', 'designation_end_entity_type']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_misplaced_end_designations" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'name' in params:
            query_params.append(('name', params['name']))  # noqa: E501
        if 'designation_end_entity_type' in params:
            query_params.append(('designation_end_entity_type', params['designation_end_entity_type']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/synonyms/misplaced-end-designations', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SynonymList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_number_words(self, **kwargs):  # noqa: E501
        """get_number_words  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_number_words(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: SynonymList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_number_words_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_number_words_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_number_words_with_http_info(self, **kwargs):  # noqa: E501
        """get_number_words  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_number_words_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: SynonymList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_number_words" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/synonyms/number-words', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SynonymList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_prefixes(self, **kwargs):  # noqa: E501
        """get_prefixes  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_prefixes(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: SynonymList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_prefixes_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_prefixes_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_prefixes_with_http_info(self, **kwargs):  # noqa: E501
        """get_prefixes  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_prefixes_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: SynonymList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_prefixes" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/synonyms/prefixes', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SynonymList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_regex_prefixes(self, **kwargs):  # noqa: E501
        """get_regex_prefixes  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_regex_prefixes(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str text: 
        :param str prefixes_str: 
        :return: String
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_regex_prefixes_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_regex_prefixes_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_regex_prefixes_with_http_info(self, **kwargs):  # noqa: E501
        """get_regex_prefixes  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_regex_prefixes_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str text: 
        :param str prefixes_str: 
        :return: String
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['text', 'prefixes_str']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_regex_prefixes" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'text' in params:
            query_params.append(('text', params['text']))  # noqa: E501
        if 'prefixes_str' in params:
            query_params.append(('prefixes_str', params['prefixes_str']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/synonyms/regex-prefixes', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='String',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_stop_words(self, **kwargs):  # noqa: E501
        """get_stop_words  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_stop_words(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str word: 
        :return: SynonymList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_stop_words_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_stop_words_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_stop_words_with_http_info(self, **kwargs):  # noqa: E501
        """get_stop_words  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_stop_words_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str word: 
        :return: SynonymList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['word']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_stop_words" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'word' in params:
            query_params.append(('word', params['word']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/synonyms/stop-words', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SynonymList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_synonyms(self, col, term, **kwargs):  # noqa: E501
        """get_synonyms  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_synonyms(col, term, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str col: (required)
        :param str term: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_synonyms_with_http_info(col, term, **kwargs)  # noqa: E501
        else:
            (data) = self.get_synonyms_with_http_info(col, term, **kwargs)  # noqa: E501
            return data

    def get_synonyms_with_http_info(self, col, term, **kwargs):  # noqa: E501
        """get_synonyms  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_synonyms_with_http_info(col, term, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str col: (required)
        :param str term: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['col', 'term']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_synonyms" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'col' is set
        if ('col' not in params or
                params['col'] is None):
            raise ValueError("Missing the required parameter `col` when calling `get_synonyms`")  # noqa: E501
        # verify the required parameter 'term' is set
        if ('term' not in params or
                params['term'] is None):
            raise ValueError("Missing the required parameter `term` when calling `get_synonyms`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'col' in params:
            path_params['col'] = params['col']  # noqa: E501
        if 'term' in params:
            path_params['term'] = params['term']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/synonyms/{col}/{term}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_transform_text(self, **kwargs):  # noqa: E501
        """get_transform_text  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_transform_text(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str text: 
        :param str designation_all: 
        :param str prefix_list: 
        :param str number_list: 
        :param str exceptions_ws: 
        :return: String
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_transform_text_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_transform_text_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_transform_text_with_http_info(self, **kwargs):  # noqa: E501
        """get_transform_text  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_transform_text_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str text: 
        :param str designation_all: 
        :param str prefix_list: 
        :param str number_list: 
        :param str exceptions_ws: 
        :return: String
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['text', 'designation_all', 'prefix_list', 'number_list', 'exceptions_ws']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_transform_text" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'text' in params:
            query_params.append(('text', params['text']))  # noqa: E501
        if 'designation_all' in params:
            query_params.append(('designation_all', params['designation_all']))  # noqa: E501
        if 'prefix_list' in params:
            query_params.append(('prefix_list', params['prefix_list']))  # noqa: E501
        if 'number_list' in params:
            query_params.append(('number_list', params['number_list']))  # noqa: E501
        if 'exceptions_ws' in params:
            query_params.append(('exceptions_ws', params['exceptions_ws']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/synonyms/transform-text', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='String',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_word_substitutions(self, **kwargs):  # noqa: E501
        """get_word_substitutions  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_word_substitutions(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str word: 
        :return: SynonymList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_word_substitutions_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_word_substitutions_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_word_substitutions_with_http_info(self, **kwargs):  # noqa: E501
        """get_word_substitutions  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_word_substitutions_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str word: 
        :return: SynonymList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['word']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_word_substitutions" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'word' in params:
            query_params.append(('word', params['word']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/synonyms/substitutions', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SynonymList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_word_synonyms(self, **kwargs):  # noqa: E501
        """get_word_synonyms  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_word_synonyms(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str word: 
        :return: SynonymList
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_word_synonyms_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_word_synonyms_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_word_synonyms_with_http_info(self, **kwargs):  # noqa: E501
        """get_word_synonyms  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_word_synonyms_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str word: 
        :return: SynonymList
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['word']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_word_synonyms" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'word' in params:
            query_params.append(('word', params['word']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/synonyms/synonyms', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SynonymList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
